'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { dictionary, packages, type Lang } from '@/lib/content';
type Copy = (typeof dictionary)[Lang];
import { Icon } from './icons';

function Button({ href, children, light=false }: { href:string; children:React.ReactNode; light?:boolean }) { return <Link className={`shine inline-flex items-center gap-2 rounded-full px-6 py-3 text-sm font-semibold transition duration-300 ${light?'bg-white text-[#6C0B1C] hover:bg-[#F5F1EE]':'bg-[#6C0B1C] text-white shadow-xl shadow-[#6C0B1C]/20 hover:bg-[#5A0917] hover:-translate-y-0.5'}`} href={href}>{children}<Icon name="arrow" className="h-4 w-4" /></Link> }

export function Site({ initialLang='de' as Lang, contactOnly=false, selectedPackage='' }) {
 const [lang,setLang]=useState<Lang>(initialLang); const [active,setActive]=useState('home'); const t=dictionary[lang];
 useEffect(()=>{ const ids=['home','services','contact']; const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-35% 0px -55%'}); ids.forEach(id=>{const el=document.getElementById(id); if(el) obs.observe(el)}); return()=>obs.disconnect()},[]);
 const nav=[['home',t.nav.home],['services',t.nav.services],['contact',t.nav.contact]];
 return <div className="min-h-screen overflow-hidden bg-[#FAF8F6] text-[#1B1B1B]">
  <header className="fixed inset-x-0 top-0 z-50 px-4 py-4"><nav className="glass mx-auto flex max-w-7xl items-center justify-between rounded-full px-5 py-3 luxury-shadow" aria-label="Main"><Link href="/#home" className="relative h-8 w-28"><Image src="/logos/floren_text_only_withoutbg.png" alt="Floren" fill className="object-contain" priority sizes="112px"/></Link><div className="hidden items-center gap-1 md:flex">{nav.map(([id,label])=><Link key={id} href={id==='contact'?'/contact':`/#${id}`} className={`rounded-full px-4 py-2 text-sm transition ${active===id?'bg-[#6C0B1C] text-white':'text-[#5E5E5E] hover:bg-white hover:text-[#1B1B1B]'}`}>{label}</Link>)}</div><div className="flex rounded-full border border-[#E8E2DC] bg-white p-1 text-xs font-bold"><button onClick={()=>setLang('de')} className={`rounded-full px-3 py-1.5 ${lang==='de'?'bg-[#480713] text-white':'text-[#5E5E5E]'}`}>DE</button><button onClick={()=>setLang('en')} className={`rounded-full px-3 py-1.5 ${lang==='en'?'bg-[#480713] text-white':'text-[#5E5E5E]'}`}>EN</button></div></nav></header>
  <main>{contactOnly ? <Contact lang={lang} selectedPackage={selectedPackage}/> : <><Hero t={t}/><Intro t={t}/><Services t={t}/><Contact lang={lang}/></>}</main><Footer t={t}/>
 </div>
}
function Hero({t}:{t:Copy}){return <section id="home" className="relative min-h-screen px-6 pt-36"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_20%_20%,rgba(201,164,90,.22),transparent_28%),radial-gradient(circle_at_80%_10%,rgba(108,11,28,.16),transparent_30%)]"/><Image src="/logos/brandmark_withoutbg.png" alt="" width={420} height={420} className="float absolute right-[-120px] top-32 -z-10 opacity-10" priority/><div className="mx-auto grid max-w-7xl items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr]"><div className="reveal"><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#E8E2DC] bg-white/70 px-4 py-2 text-sm text-[#6C0B1C]"><Icon name="sparkle" className="h-4 w-4 text-[#C9A45A]" />{t.hero.eyebrow}</p><h1 className="font-serif text-6xl leading-[.92] tracking-[-.04em] text-[#1B1B1B] md:text-8xl">{t.hero.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#5E5E5E]">{t.hero.text}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button href="/contact">{t.hero.cta}</Button><Button href="/#services" light>{t.hero.secondary}</Button></div></div><div className="reveal glass relative rounded-[2.5rem] p-8 luxury-shadow"><Image src="/logos/floren_full_color_withoutbg.png" alt="Floren brand" width={620} height={360} className="mx-auto h-auto w-full" priority/><div className="gold-line mt-8 h-px"/><p className="mt-6 text-center font-serif text-3xl text-[#480713]">Social presence, curated with restraint.</p></div></div></section>}
function Intro({t}:{t:Copy}){return <section className="px-6 py-24"><div className="mx-auto max-w-5xl text-center"><h2 className="font-serif text-5xl tracking-[-.03em] md:text-7xl">{t.intro.title}</h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-[#5E5E5E]">{t.intro.text}</p></div></section>}
function Services({t}:{t:Copy}){return <section id="services" className="bg-[#F5F1EE] px-6 py-28"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[.3em] text-[#C9A45A]">{t.services.eyebrow}</p><div className="mt-4 grid gap-6 lg:grid-cols-[.8fr_1fr]"><h2 className="font-serif text-5xl tracking-[-.03em] md:text-7xl">{t.services.title}</h2><p className="text-lg leading-8 text-[#5E5E5E]">{t.services.text}</p></div><div className="mt-14 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{packages.map((p,i)=><article key={p.id} className={`group reveal flex min-h-[520px] flex-col rounded-[2rem] border border-[#E8E2DC] bg-white p-7 transition duration-300 hover:-translate-y-2 hover:shadow-2xl ${i===2?'ring-1 ring-[#C9A45A]':''}`}><div className="mb-8 flex items-start justify-between"><h3 className="font-serif text-4xl text-[#480713]">{p.name}</h3><span className="rounded-full bg-[#FAF8F6] p-3 text-[#C9A45A]"><Icon name="sparkle" className="h-5 w-5"/></span></div><p className="text-sm leading-7 text-[#5E5E5E]">{p.description}</p><p className="mt-8 font-serif text-4xl">{p.price}</p><ul className="mt-8 space-y-3">{p.features.map(f=><li key={f} className="flex gap-3 text-sm text-[#5E5E5E]"><Icon name="check" className="mt-0.5 h-4 w-4 shrink-0 text-[#6C0B1C]"/>{f}</li>)}</ul><div className="mt-auto pt-8"><Button href={`/contact?package=${encodeURIComponent(p.id)}`}>{t.services.cta}</Button></div></article>)}</div></div></section>}
export function Contact({lang,selectedPackage=''}:{lang:Lang;selectedPackage?:string}){const t=dictionary[lang].contact; const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle'); const packageName=useMemo(()=>packages.find(p=>p.id===selectedPackage)?.name || '',[selectedPackage]); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('sending'); const fd=new FormData(e.currentTarget); const body=Object.fromEntries(fd); const res=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); setStatus(res.ok?'success':'error'); if(res.ok)e.currentTarget.reset()} return <section id="contact" className="px-6 py-28"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[.8fr_1fr]"><div><h1 className="font-serif text-5xl tracking-[-.03em] md:text-7xl">{t.title}</h1><p className="mt-6 text-lg leading-8 text-[#5E5E5E]">{t.text}</p><div className="mt-8 rounded-3xl border border-[#E8E2DC] bg-white p-6"><p className="text-sm text-[#5E5E5E]">{packageName?t.package:t.noPackage}</p><p className="mt-1 font-serif text-3xl text-[#6C0B1C]">{packageName || 'Floren'}</p></div></div><form onSubmit={submit} className="glass grid gap-4 rounded-[2rem] p-5 md:p-8"><input type="hidden" name="package" value={packageName}/>{['name','company','email','phone'].map(k=><label key={k} className="text-sm font-medium text-[#5E5E5E]">{t[k as keyof Pick<typeof t, 'name' | 'company' | 'email' | 'phone'>]}<input required type={k==='email'?'email':'text'} name={k} className="mt-2 w-full rounded-2xl border border-[#E8E2DC] bg-white px-4 py-3 outline-none transition focus:border-[#6C0B1C]"/></label>)}<label className="text-sm font-medium text-[#5E5E5E]">{t.message}<textarea required name="message" minLength={10} rows={5} className="mt-2 w-full resize-none rounded-2xl border border-[#E8E2DC] bg-white px-4 py-3 outline-none transition focus:border-[#6C0B1C]"/></label><button disabled={status==='sending'} className="shine mt-2 inline-flex items-center justify-center gap-2 rounded-full bg-[#6C0B1C] px-6 py-4 font-semibold text-white transition hover:bg-[#5A0917] disabled:opacity-60"><Icon name="send" className="h-4 w-4"/>{status==='sending'?t.sending:t.send}</button>{status==='success'&&<p className="text-sm text-green-700">{t.success}</p>}{status==='error'&&<p className="text-sm text-red-700">{t.error}</p>}</form></div></section>}
function Footer({t}:{t:Copy}){return <footer className="border-t border-[#E8E2DC] bg-white px-6 py-12"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-center md:justify-between"><Image src="/logos/floren_full_color_withoutbg.png" alt="Floren" width={170} height={80}/><div className="flex gap-5 text-sm text-[#5E5E5E]"><span>{t.footer.legal}</span><Link href="/privacy">{t.footer.privacy}</Link><Link href="/imprint">{t.footer.imprint}</Link></div></div></footer>}
